"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BbTTX1hYAlE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { CartesianGrid, XAxis, Line, LineChart } from "recharts";
import {
  ChartTooltipContent,
  ChartTooltip,
  ChartContainer,
} from "@/components/ui/chart";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ChartCard } from "@/components/charts/national_epidemic/ChartCard";
import { TrendingUp } from "lucide-react";

function Header() {
  return (
    <header className="bg-white shadow">
      <div className="container mx-auto px-4 py-6 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold leading-tight text-foreground">
          A Summary of COVID-19 Data in Malaysia
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Last updated on Friday, 10 December 2021 at 4:00pm
        </p>
      </div>
    </header>
  );
}

type DashboardChartCardProps = {
  title: string;
  description: string;
  footer?: string;
  children?: React.ReactNode;
};

function DashboardChartCard({
  title,
  description,
  footer,
  children,
}: DashboardChartCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent></CardContent>
      {footer && (
        <CardFooter>
          <div className="flex w-full items-start gap-2 text-sm">
            <div className="grid gap-2">
              <div className="flex items-center gap-2 font-medium leading-none">
                Trending up by 5.2% this month{" "}
                <TrendingUp className="h-4 w-4" />
              </div>
              <div className="flex items-center gap-2 leading-none text-muted-foreground">
                January - June 2024
              </div>
            </div>
          </div>
        </CardFooter>
      )}
    </Card>
  );
}

const CardText = {
  vaccinations: {
    title: "People Vaccinated",
    description: "A summary of the number of people vaccinated.",
    footer: "All vaccinations data",
  },
};

export default function DashboardPage() {
  // Fetch a ton of data here
  // Pass it into cases card, deaths card, testing card, vaccinations card, hospitalizations card
  return (
    <div className="min-h-screen bg-muted/50">
      <Header />
      <div className="container mx-auto mt-8 h-screen w-screen">
        <main className="grid grid-flow-row-dense grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
          <Card className="col-span-2 row-span-1 rounded-lg bg-card p-6 shadow">
            <CardHeader>
              <CardTitle className="text-2xl font-bold">Testing Data</CardTitle>
              <CardDescription>Data collected up to </CardDescription>
            </CardHeader>
            <CardContent>
              <p>Card Content</p>
            </CardContent>
            <CardFooter>
              <p>Card Footer</p>
            </CardFooter>
          </Card>
          <Card className="col-span-1 row-span-2 rounded-lg bg-card p-6 shadow">
            <CardHeader>
              <CardTitle className="text-2xl font-bold">Deaths</CardTitle>
              <CardDescription>Data collected up to </CardDescription>
            </CardHeader>
            <CardContent>
              <p>Card Content</p>
            </CardContent>
            <CardFooter>
              <p>Card Footer</p>
            </CardFooter>
          </Card>
          <section className="col-span-2 rounded-lg bg-card p-6 shadow">
            <h2 className="mb-4 text-xl font-bold">Hospitalizations</h2>
            <div className="col-span-2 grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm text-muted-foreground">
                  Daily - first dose
                </p>
                <p className="text-2xl font-bold">24,039</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">
                  Daily - second dose
                </p>
                <p className="text-2xl font-bold">33,824</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">
                  Daily - booster or third dose
                </p>
                <p className="text-2xl font-bold">469,479</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">
                  Total - first dose
                </p>
                <p className="text-2xl font-bold">51,207,496</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">
                  Total - second dose
                </p>
                <p className="text-2xl font-bold">46,674,061</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">
                  Total - booster or third dose
                </p>
                <p className="text-2xl font-bold">22,184,983</p>
              </div>
            </div>
            <a
              href="#"
              className="mt-4 block text-blue-500 hover:text-blue-700"
            >
              All vaccinations data
            </a>
          </section>
          <section className="rounded-lg bg-white p-6 shadow">
            <h2 className="mb-4 text-xl font-bold">People Tested Positive</h2>
            <p className="text-sm text-muted-foreground">
              Latest data provided on 10 December 2021
            </p>
            <p className="mt-2 text-2xl font-bold">Daily: 58,194</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Last 7 days: 344,393
            </p>
            <p className="mt-1 text-sm text-red-500">+31,943 (10.2%)</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Rate per 100,000 people: 498
            </p>
            <LinechartChart className="mt-4 h-32 w-full" />
            <a
              href="#"
              className="mt-4 block text-blue-500 hover:text-blue-700"
            >
              All cases data
            </a>
          </section>
          <section className="rounded-lg bg-white p-6 shadow">
            <h2 className="mb-4 text-xl font-bold">
              Deaths within 28 days of positive test
            </h2>
            <p className="text-sm text-muted-foreground">
              Latest data provided on 10 December 2021
            </p>
            <p className="mt-2 text-2xl font-bold">Daily: 120</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Last 7 days: 831
            </p>
            <p className="mt-1 text-sm text-muted-foreground">No change</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Rate per 100,000 people: 1.1
            </p>
            <LinechartChart className="mt-4 h-32 w-full" />
            <a
              href="#"
              className="mt-4 block text-blue-500 hover:text-blue-700"
            >
              All deaths data
            </a>
          </section>
          <section className="rounded-lg bg-white p-6 shadow">
            <h2 className="mb-4 text-xl font-bold">Patients Admitted</h2>
            <p className="text-sm text-muted-foreground">
              Latest data provided on 6 December 2021
            </p>
            <p className="mt-2 text-2xl font-bold">Daily: 839</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Last 7 days: 5,556
            </p>
            <p className="mt-1 text-sm text-red-500">+196 (3.7%)</p>
            <LinechartChart className="mt-4 h-32 w-full" />
            <a
              href="#"
              className="mt-4 block text-blue-500 hover:text-blue-700"
            >
              All healthcare data
            </a>
          </section>
          <section className="rounded-lg bg-white p-6 shadow">
            <h2 className="mb-4 text-xl font-bold">Virus Tests Conducted</h2>
            <p className="text-sm text-muted-foreground">
              Latest data provided on 9 December 2021
            </p>
            <p className="mt-2 text-2xl font-bold">Daily: 1,326,438</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Last 7 days: 7,841,865
            </p>
            <p className="mt-1 text-sm text-green-500">+879,735 (12.6%)</p>
            <LinechartChart className="mt-4 h-32 w-full" />
            <a
              href="#"
              className="mt-4 block text-blue-500 hover:text-blue-700"
            >
              All testing data
            </a>
          </section>
        </main>
      </div>
    </div>
  );
}

function LinechartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
      >
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip
            cursor={false}
            content={<ChartTooltipContent hideLabel />}
          />
          <Line
            dataKey="desktop"
            type="natural"
            stroke="var(--color-desktop)"
            strokeWidth={2}
            dot={false}
          />
        </LineChart>
      </ChartContainer>
    </div>
  );
}
